name: Ejemplo de composite Action

on:
  push:
    branches: 
      - main 
      - develop
  
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    env:
      MY_VAR: Mi variable de entorno

    steps:
      - name: Test
        env:
          STEP_MY_VAR: Nivel Step
        run: |
          echo "Dicho valor es $MY_VAR"
          echo "Dicho valor es $STEP_MY_VAR"
          echo "Dicho valor ${{ vars.MY_VARIABLE_PAGE }}"
          echo "Dicho valor ${{ secrets.MY_SECRET_VAR }}"

      - name: SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 127.0.1.1 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts