name: test

on:
  push:
    branches: 
      - main 
      - develop
  
jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: ls
        run: ls -al

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
    
      - name: node version
        run: node --version
      
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'

      - name: PHP version
        run: php --version
    