name: test

on:
  push:
    branches: 
      - main 
      - develop
  
jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: ls
        run: |
          chmod +x script.sh
          ./script.sh
