name: Ejemplo de composite Action

on:
  push:
    branches: 
      - main 
      - develop
  
  pull_request:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    env:
      MY_VAR: Mi variable de entorno

    steps:
      - name: Test
        env:
          STEP_MY_VAR: Nivel Step
        run: |
          echo "Dicho valor es $MY_VAR"
          echo "Dicho valor es $STEP_MY_VAR"